// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/pb/repo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_pkg_pb_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_pkg_pb_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_pkg_pb_repo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UploadVideoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadVideoRequest_Metadata
	//	*UploadVideoRequest_Chunk
	Data          isUploadVideoRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_pkg_pb_repo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{3}
}

func (x *UploadVideoRequest) GetData() isUploadVideoRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadVideoRequest) GetMetadata() *VideoMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadVideoRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadVideoRequest) GetChunk() *VideoChunk {
	if x != nil {
		if x, ok := x.Data.(*UploadVideoRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadVideoRequest_Data interface {
	isUploadVideoRequest_Data()
}

type UploadVideoRequest_Metadata struct {
	Metadata *VideoMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadVideoRequest_Chunk struct {
	Chunk *VideoChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadVideoRequest_Metadata) isUploadVideoRequest_Data() {}

func (*UploadVideoRequest_Chunk) isUploadVideoRequest_Data() {}

type VideoMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMetadata) Reset() {
	*x = VideoMetadata{}
	mi := &file_pkg_pb_repo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadata) ProtoMessage() {}

func (x *VideoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadata.ProtoReflect.Descriptor instead.
func (*VideoMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{4}
}

func (x *VideoMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VideoMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *VideoMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type VideoChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoChunk) Reset() {
	*x = VideoChunk{}
	mi := &file_pkg_pb_repo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoChunk) ProtoMessage() {}

func (x *VideoChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoChunk.ProtoReflect.Descriptor instead.
func (*VideoChunk) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{5}
}

func (x *VideoChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *VideoChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetLast3UserVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLast3UserVideosRequest) Reset() {
	*x = GetLast3UserVideosRequest{}
	mi := &file_pkg_pb_repo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLast3UserVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLast3UserVideosRequest) ProtoMessage() {}

func (x *GetLast3UserVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLast3UserVideosRequest.ProtoReflect.Descriptor instead.
func (*GetLast3UserVideosRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{6}
}

func (x *GetLast3UserVideosRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserVideosRequest) Reset() {
	*x = GetUserVideosRequest{}
	mi := &file_pkg_pb_repo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserVideosRequest) ProtoMessage() {}

func (x *GetUserVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserVideosRequest.ProtoReflect.Descriptor instead.
func (*GetUserVideosRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserVideosRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_pkg_pb_repo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{8}
}

func (x *GetVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type DownloadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoRequest) Reset() {
	*x = DownloadVideoRequest{}
	mi := &file_pkg_pb_repo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoRequest) ProtoMessage() {}

func (x *DownloadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoRequest.ProtoReflect.Descriptor instead.
func (*DownloadVideoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadVideoRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type VideoMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FileName      string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMetadataResponse) Reset() {
	*x = VideoMetadataResponse{}
	mi := &file_pkg_pb_repo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadataResponse) ProtoMessage() {}

func (x *VideoMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadataResponse.ProtoReflect.Descriptor instead.
func (*VideoMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{10}
}

func (x *VideoMetadataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoMetadataResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VideoMetadataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoMetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VideoMetadataResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *VideoMetadataResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type Video3ListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Videos        []*VideoMetadataResponse `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video3ListResponse) Reset() {
	*x = Video3ListResponse{}
	mi := &file_pkg_pb_repo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video3ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video3ListResponse) ProtoMessage() {}

func (x *Video3ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video3ListResponse.ProtoReflect.Descriptor instead.
func (*Video3ListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{11}
}

func (x *Video3ListResponse) GetVideos() []*VideoMetadataResponse {
	if x != nil {
		return x.Videos
	}
	return nil
}

type VideoListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Videos        []*VideoMetadataResponse `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoListResponse) Reset() {
	*x = VideoListResponse{}
	mi := &file_pkg_pb_repo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoListResponse) ProtoMessage() {}

func (x *VideoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoListResponse.ProtoReflect.Descriptor instead.
func (*VideoListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{12}
}

func (x *VideoListResponse) GetVideos() []*VideoMetadataResponse {
	if x != nil {
		return x.Videos
	}
	return nil
}

type VideoFileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*VideoFileResponse_Metadata
	//	*VideoFileResponse_Chunk
	Data          isVideoFileResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFileResponse) Reset() {
	*x = VideoFileResponse{}
	mi := &file_pkg_pb_repo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFileResponse) ProtoMessage() {}

func (x *VideoFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFileResponse.ProtoReflect.Descriptor instead.
func (*VideoFileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{13}
}

func (x *VideoFileResponse) GetData() isVideoFileResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoFileResponse) GetMetadata() *VideoFileMetadata {
	if x != nil {
		if x, ok := x.Data.(*VideoFileResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *VideoFileResponse) GetChunk() *VideoFileChunk {
	if x != nil {
		if x, ok := x.Data.(*VideoFileResponse_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isVideoFileResponse_Data interface {
	isVideoFileResponse_Data()
}

type VideoFileResponse_Metadata struct {
	Metadata *VideoFileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type VideoFileResponse_Chunk struct {
	Chunk *VideoFileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*VideoFileResponse_Metadata) isVideoFileResponse_Data() {}

func (*VideoFileResponse_Chunk) isVideoFileResponse_Data() {}

type VideoFileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,2,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFileMetadata) Reset() {
	*x = VideoFileMetadata{}
	mi := &file_pkg_pb_repo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFileMetadata) ProtoMessage() {}

func (x *VideoFileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFileMetadata.ProtoReflect.Descriptor instead.
func (*VideoFileMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{14}
}

func (x *VideoFileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *VideoFileMetadata) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *VideoFileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type VideoFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunk_number,json=chunkNumber,proto3" json:"chunk_number,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoFileChunk) Reset() {
	*x = VideoFileChunk{}
	mi := &file_pkg_pb_repo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFileChunk) ProtoMessage() {}

func (x *VideoFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_repo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFileChunk.ProtoReflect.Descriptor instead.
func (*VideoFileChunk) Descriptor() ([]byte, []int) {
	return file_pkg_pb_repo_proto_rawDescGZIP(), []int{15}
}

func (x *VideoFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VideoFileChunk) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *VideoFileChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

var File_pkg_pb_repo_proto protoreflect.FileDescriptor

const file_pkg_pb_repo_proto_rawDesc = "" +
	"\n" +
	"\x11pkg/pb/repo.proto\x12\x04repo\x1a\x1bgoogle/protobuf/empty.proto\"a\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"H\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"u\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"y\n" +
	"\x12UploadVideoRequest\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x13.repo.VideoMetadataH\x00R\bmetadata\x12(\n" +
	"\x05chunk\x18\x02 \x01(\v2\x10.repo.VideoChunkH\x00R\x05chunkB\x06\n" +
	"\x04data\"\x9a\x01\n" +
	"\rVideoMetadata\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\"`\n" +
	"\n" +
	"VideoChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"4\n" +
	"\x19GetLast3UserVideosRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x14GetUserVideosRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\x0fGetVideoRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"3\n" +
	"\x14DownloadVideoRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"\xb4\x01\n" +
	"\x15VideoMetadataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\"I\n" +
	"\x12Video3ListResponse\x123\n" +
	"\x06videos\x18\x01 \x03(\v2\x1b.repo.VideoMetadataResponseR\x06videos\"H\n" +
	"\x11VideoListResponse\x123\n" +
	"\x06videos\x18\x01 \x03(\v2\x1b.repo.VideoMetadataResponseR\x06videos\"\x80\x01\n" +
	"\x11VideoFileResponse\x125\n" +
	"\bmetadata\x18\x01 \x01(\v2\x17.repo.VideoFileMetadataH\x00R\bmetadata\x12,\n" +
	"\x05chunk\x18\x02 \x01(\v2\x14.repo.VideoFileChunkH\x00R\x05chunkB\x06\n" +
	"\x04data\"p\n" +
	"\x11VideoFileMetadata\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\x02 \x01(\x03R\bfileSize\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"`\n" +
	"\x0eVideoFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fchunk_number\x18\x02 \x01(\x05R\vchunkNumber\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast2\xa6\x04\n" +
	"\vRepoService\x129\n" +
	"\n" +
	"CreateUser\x12\x17.repo.CreateUserRequest\x1a\x12.repo.UserResponse\x123\n" +
	"\aGetUser\x12\x14.repo.GetUserRequest\x1a\x12.repo.UserResponse\x12F\n" +
	"\vUploadVideo\x12\x18.repo.UploadVideoRequest\x1a\x1b.repo.VideoMetadataResponse(\x01\x12D\n" +
	"\rGetUserVideos\x12\x1a.repo.GetUserVideosRequest\x1a\x17.repo.VideoListResponse\x12O\n" +
	"\x12GetLast3UserVideos\x12\x1f.repo.GetLast3UserVideosRequest\x1a\x18.repo.Video3ListResponse\x12B\n" +
	"\fGetVideoByID\x12\x15.repo.GetVideoRequest\x1a\x1b.repo.VideoMetadataResponse\x12F\n" +
	"\rDownloadVideo\x12\x1a.repo.DownloadVideoRequest\x1a\x17.repo.VideoFileResponse0\x01\x12<\n" +
	"\vRemoveVideo\x12\x15.repo.GetVideoRequest\x1a\x16.google.protobuf.EmptyB(Z&github.com/lumbrjx/codek7/repo/pkg/pb/b\x06proto3"

var (
	file_pkg_pb_repo_proto_rawDescOnce sync.Once
	file_pkg_pb_repo_proto_rawDescData []byte
)

func file_pkg_pb_repo_proto_rawDescGZIP() []byte {
	file_pkg_pb_repo_proto_rawDescOnce.Do(func() {
		file_pkg_pb_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_repo_proto_rawDesc), len(file_pkg_pb_repo_proto_rawDesc)))
	})
	return file_pkg_pb_repo_proto_rawDescData
}

var file_pkg_pb_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_pb_repo_proto_goTypes = []any{
	(*CreateUserRequest)(nil),         // 0: repo.CreateUserRequest
	(*GetUserRequest)(nil),            // 1: repo.GetUserRequest
	(*UserResponse)(nil),              // 2: repo.UserResponse
	(*UploadVideoRequest)(nil),        // 3: repo.UploadVideoRequest
	(*VideoMetadata)(nil),             // 4: repo.VideoMetadata
	(*VideoChunk)(nil),                // 5: repo.VideoChunk
	(*GetLast3UserVideosRequest)(nil), // 6: repo.GetLast3UserVideosRequest
	(*GetUserVideosRequest)(nil),      // 7: repo.GetUserVideosRequest
	(*GetVideoRequest)(nil),           // 8: repo.GetVideoRequest
	(*DownloadVideoRequest)(nil),      // 9: repo.DownloadVideoRequest
	(*VideoMetadataResponse)(nil),     // 10: repo.VideoMetadataResponse
	(*Video3ListResponse)(nil),        // 11: repo.Video3ListResponse
	(*VideoListResponse)(nil),         // 12: repo.VideoListResponse
	(*VideoFileResponse)(nil),         // 13: repo.VideoFileResponse
	(*VideoFileMetadata)(nil),         // 14: repo.VideoFileMetadata
	(*VideoFileChunk)(nil),            // 15: repo.VideoFileChunk
	(*emptypb.Empty)(nil),             // 16: google.protobuf.Empty
}
var file_pkg_pb_repo_proto_depIdxs = []int32{
	4,  // 0: repo.UploadVideoRequest.metadata:type_name -> repo.VideoMetadata
	5,  // 1: repo.UploadVideoRequest.chunk:type_name -> repo.VideoChunk
	10, // 2: repo.Video3ListResponse.videos:type_name -> repo.VideoMetadataResponse
	10, // 3: repo.VideoListResponse.videos:type_name -> repo.VideoMetadataResponse
	14, // 4: repo.VideoFileResponse.metadata:type_name -> repo.VideoFileMetadata
	15, // 5: repo.VideoFileResponse.chunk:type_name -> repo.VideoFileChunk
	0,  // 6: repo.RepoService.CreateUser:input_type -> repo.CreateUserRequest
	1,  // 7: repo.RepoService.GetUser:input_type -> repo.GetUserRequest
	3,  // 8: repo.RepoService.UploadVideo:input_type -> repo.UploadVideoRequest
	7,  // 9: repo.RepoService.GetUserVideos:input_type -> repo.GetUserVideosRequest
	6,  // 10: repo.RepoService.GetLast3UserVideos:input_type -> repo.GetLast3UserVideosRequest
	8,  // 11: repo.RepoService.GetVideoByID:input_type -> repo.GetVideoRequest
	9,  // 12: repo.RepoService.DownloadVideo:input_type -> repo.DownloadVideoRequest
	8,  // 13: repo.RepoService.RemoveVideo:input_type -> repo.GetVideoRequest
	2,  // 14: repo.RepoService.CreateUser:output_type -> repo.UserResponse
	2,  // 15: repo.RepoService.GetUser:output_type -> repo.UserResponse
	10, // 16: repo.RepoService.UploadVideo:output_type -> repo.VideoMetadataResponse
	12, // 17: repo.RepoService.GetUserVideos:output_type -> repo.VideoListResponse
	11, // 18: repo.RepoService.GetLast3UserVideos:output_type -> repo.Video3ListResponse
	10, // 19: repo.RepoService.GetVideoByID:output_type -> repo.VideoMetadataResponse
	13, // 20: repo.RepoService.DownloadVideo:output_type -> repo.VideoFileResponse
	16, // 21: repo.RepoService.RemoveVideo:output_type -> google.protobuf.Empty
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_pb_repo_proto_init() }
func file_pkg_pb_repo_proto_init() {
	if File_pkg_pb_repo_proto != nil {
		return
	}
	file_pkg_pb_repo_proto_msgTypes[3].OneofWrappers = []any{
		(*UploadVideoRequest_Metadata)(nil),
		(*UploadVideoRequest_Chunk)(nil),
	}
	file_pkg_pb_repo_proto_msgTypes[13].OneofWrappers = []any{
		(*VideoFileResponse_Metadata)(nil),
		(*VideoFileResponse_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_repo_proto_rawDesc), len(file_pkg_pb_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_repo_proto_goTypes,
		DependencyIndexes: file_pkg_pb_repo_proto_depIdxs,
		MessageInfos:      file_pkg_pb_repo_proto_msgTypes,
	}.Build()
	File_pkg_pb_repo_proto = out.File
	file_pkg_pb_repo_proto_goTypes = nil
	file_pkg_pb_repo_proto_depIdxs = nil
}
